var searchData=
[
  ['register',['register',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_user_authentication___a_p_i.html#a78853d00e5c78106189b76da83329bab',1,'com::EasyRestaurantClient::app::UserAuthentication_API']]],
  ['remove_5freservation',['remove_reservation',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reservations___a_p_i.html#a120f97f41046783080574c36464369b0',1,'com::EasyRestaurantClient::app::Reservations_API']]],
  ['reservation',['Reservation',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reservation.html',1,'com.EasyRestaurantClient.app.Reservation'],['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reservation.html#a2b41c3f3b0c4c91a7538e43a6d61c095',1,'com.EasyRestaurantClient.app.Reservation.Reservation()']]],
  ['reservation_2ejava',['Reservation.java',['../_reservation_8java.html',1,'']]],
  ['reservation_5flist',['reservation_list',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reservations___a_p_i.html#a6664f77ff356233914e90cb4c7cef544',1,'com::EasyRestaurantClient::app::Reservations_API']]],
  ['reservations_5fapi',['Reservations_API',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reservations___a_p_i.html',1,'com::EasyRestaurantClient::app']]],
  ['reservations_5fapi_2ejava',['Reservations_API.java',['../_reservations___a_p_i_8java.html',1,'']]],
  ['restaurant',['Restaurant',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_restaurant.html',1,'com.EasyRestaurantClient.app.Restaurant'],['../classcom_1_1_easy_restaurant_client_1_1app_1_1_restaurant.html#a7ffb540391f38586ca8c8c097aee82c9',1,'com.EasyRestaurantClient.app.Restaurant.Restaurant()']]],
  ['restaurant_2ejava',['Restaurant.java',['../_restaurant_8java.html',1,'']]],
  ['restaurant_5flist',['restaurant_list',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_restaurants___a_p_i.html#a6a47ac3c519747a720edff6505bacfd1',1,'com::EasyRestaurantClient::app::Restaurants_API']]],
  ['restaurants_5fapi',['Restaurants_API',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_restaurants___a_p_i.html',1,'com::EasyRestaurantClient::app']]],
  ['restaurants_5fapi_2ejava',['Restaurants_API.java',['../_restaurants___a_p_i_8java.html',1,'']]],
  ['reviews_5fapi',['Reviews_API',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reviews___a_p_i.html',1,'com::EasyRestaurantClient::app']]],
  ['reviews_5fapi_2ejava',['Reviews_API.java',['../_reviews___a_p_i_8java.html',1,'']]],
  ['reviews_5flist',['reviews_list',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reviews___a_p_i.html#a4ee565f9d68e8e856d69e7008bce0828',1,'com::EasyRestaurantClient::app::Reviews_API']]],
  ['reviews_5fwindow',['Reviews_Window',['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reviews___window.html',1,'com.EasyRestaurantClient.app.Reviews_Window'],['../classcom_1_1_easy_restaurant_client_1_1app_1_1_reviews___window.html#aca2dfe60f559c82bd25b555e272f484f',1,'com.EasyRestaurantClient.app.Reviews_Window.Reviews_Window()']]],
  ['reviews_5fwindow_2ejava',['Reviews_Window.java',['../_reviews___window_8java.html',1,'']]]
];
