language: python # => 1

python: # => 2
  - "3.6"

services: # => 3
  - sqlite

env: # => 4
  -DJANGO=2.2 DB=sqlite

install: # => 5
  - pip install -r EasyRestaurantsServer/requirements.txt

before_script: # => 6
  - sqlite -u root -e "CREATE DATABASE raceorganizer CHARACTER SET UTF8;"
  - sqlite -u root -e "CREATE USER 'test'@'%' IDENTIFIED BY 'test';"
  - sqlite -u root -e "GRANT ALL PRIVILEGES ON *.* to 'test'@'%';"
  - sqlite -u root -e "FLUSH PRIVILEGES"

script: # => 7
  - cd EasyRestaurantsServer
  - python manage.py test