language: python # => 1

python: # => 2
  - "3.6"

services: # => 3
  - sqlite

env: # => 4
  -DJANGO=2.2 DB=sqlite

install: # => 5
  - pip install -r EasyRestaurantsServer/requirements.txt

script: # => 7
  - cd EasyRestaurantsServer
  - python manage.py test
