# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-31 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='polls.Restaurant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='schedule',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.FloatField(blank=True),
        ),
    ]
